name: 'actions-changesets-slack-notification'
description: 'changesets 으로 배포된 패키지에 대한 알림을 slack 으로 제공합니다.'
author: 'seungjaey'

branding:
  icon: 'message-circle'
  color: 'red'

inputs:
  TITLE:
    description: 'Title'
    required: false
    default: '📦 패키지 배포 알림'

  WEB_HOOK_URL:
    description: 'Webhook URL'
    required: true
    default: ''

  OWNER:
    description: 'Owner'
    required: true
    default: ''

  AUTHOR:
    description: 'Author'
    required: true
    default: ''

  GITHUB_URL:
    description: 'Github URL'
    required: false
    default: 'https://github.com/'

  REPOSITORY_NAME:
    description: 'Repository name'
    required: true
    default: ''

  CHANGESET_MESSAGE:
    description: 'Changeset packages'
    required: true
    default: ''

runs:
  using: node20
  main: dist/index.js
